djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='hh'),
    path('', include('info_assistant.urls')),
]

info_assistant/urls.py
from django.urls import path

from . import views

# 命名空间
app_name = 'info_assistant'
urlpatterns = [

    # 搜索页面主页
    path('', views.index, name='index'),
    # 展示所有搜索结果
    path('search/', views.search, name="search"),
    # 从收藏夹里删除信息
    path('delete/<int:info_id>', views.delete_info, name="delete_info"),
    # 移动到其它收藏夹
    path('move/<int:info_id>', views.move_info_get, name="move_info"),
    # 表单
    path('move_post', views.move_info_post, name='move_info_post'),
    # 展示全部收藏夹
    path('show/', views.category_list, name='show'),
    # 展示收藏夹内容
    path('showall/<int:category_id>', views.show_category, name='showall'),
    # 创建收藏夹
    path('create/', views.create_category, name="create_category"),
    # 展示
    path('create_category/', views.create_category, name='create_category_get'),
    # 编辑收藏夹名称
    path('edit/', views.edit_category_post, name="edit_category"),
    # 展示编辑界面
    path('edit_interface/<int:id>', views.edit_category_get, name="edit_category_interface"),
    # 删除收藏夹
    path('delete_category/<int:delete_id>', views.delete_category, name="delete_category"),
    # 管理员界面
    path('enter_admin', views.enter_admin, name="enter_admin")
]

info_assistant/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    create_time = models.DateTimeField('收藏夹创建时间',default=None, null=True)

    def __str__(self):
        return self.title


class Info(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="标题", max_length=200)
    search_key = models.CharField(verbose_name="搜索关键字", max_length=32)
    url = models.CharField(verbose_name="网址", max_length=100)
    source = models.CharField(verbose_name="数据来源", max_length=32)
    category = models.ForeignKey(Category, verbose_name="所属类别", on_delete=models.CASCADE)
    create_time = models.DateTimeField('信息爬取时间', default=None, null=True)

    def __str__(self):
        return self.title

info_assistant/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Info
from .models import Category
from . import crawker
from django.utils import timezone
# Create your views here.


def index(request):
    return render(request, 'info_assistant/index.html')


def search(request):
    key_word = request.POST['keyword']
    results = crawker.get_results(key_word)
    infos = results.get('infos')
    data_analysis = results.get('data_analysis')
    d_time = timezone.now()
    category = Category.objects.create(title=key_word, create_time=d_time)
    for i in infos:
        Info.objects.create(
            title=i.get('title'),
            search_key=i.get('keyword'),
            url=i.get('url'),
            source=i.get('source'),
            category=category,
            create_time=d_time,
        )
    info_list = Info.objects.filter(category=category)
    return render(request, 'info_assistant/details.html', {'info_list': info_list, 'analysis_list': data_analysis})


# 删除收藏夹里面的信息
def delete_info(request, info_id):
    Info.objects.filter(pk=info_id).delete()
    return HttpResponseRedirect('/show')


# 移动该条信息到
def move_info_get(request, info_id):
    info = Info.objects.filter(nid=info_id).first()
    c_list = Category.objects.all()
    return render(request, 'info_assistant/move_info.html', {'info': info, 'category_list': c_list})


def move_info_post(request):
    nid = request.POST['info_id']
    new_id = request.POST['new_category_id']
    c = Category.objects.filter(pk=new_id).first()
    Info.objects.filter(pk=nid).update(category=c)
    return HttpResponseRedirect('/show')

# 按照创建时间倒序展示
def category_list(request):
    category_list = Category.objects.all().order_by('-create_time')
    return render(request, "info_assistant/myCollections.html", {'category_list': category_list})


# 展示全部的信息
def show_category(request, category_id):
    category = Category.objects.filter(pk=category_id).first()
    infos = Info.objects.filter(category=category)
    return render(request, 'info_assistant/details.html', {'info_list': infos})


# 创建一个收藏夹
def create_category(request):
    if request.method == 'POST':
        category_name = request.POST['category_name']
        Category.objects.create(title=category_name, create_time=timezone.now())
        return HttpResponseRedirect('/show')
    else:
        return render(request, 'info_assistant/create_category.html')


# 编辑收藏夹标题
def edit_category_post(request):
    category_id = request.POST.get('category_id')
    new_title = request.POST.get("new_title")
    print(category_id)
    Category.objects.filter(nid=category_id).update(title=new_title)
    return HttpResponseRedirect('/show')


def edit_category_get(request, id):
    return render(request, 'info_assistant/edit_category.html', {'id': id})


# 删除整个收藏夹
def delete_category(request, delete_id):
    Category.objects.get(pk=delete_id).delete()
    return HttpResponseRedirect('/show')


def enter_admin(request):
    return redirect('/admin')

info_assistant/templates/info_assistant/create_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h2 class="logo">
                        <a href="{% url 'info_assistant:index' %}">Python技术信息助理</a>
                    </h2>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info_assistant:index' %}">首页</a></li>
                        <li><a href="{% url 'info_assistant:show' %}">我的收藏</a></li>
                        <li><a href="{% url 'info_assistant:enter_admin' %}">管理</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <h3 class="">创建收藏夹</h3>
        <form class="navbar-form text-center" action='{% url 'info_assistant:create_category' %}' method="POST">
            {% csrf_token %}
            <div class="form-group ">
                <input type="text" name="category_name" class="form-control input-lg col-lg-12" placeholder="输入收藏夹名称">
            </div>
            <button type="submit" class="btn btn-success btn-lg">创建</button>
        </form>
    </div>


</body>
<script>

</script>
</html>

info_assistant/templates/info_assistant/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <script>
        function delete_info(id){
             var xmlhttp;
            xmlhttp=new XMLHttpRequest();
            xmlhttp.onreadystatechange=function()
            {
                if (xmlhttp.readyState==4 && xmlhttp.status==200)
                {
                    alert("删除成功")
                    location.reload()
                }
            }
            xmlhttp.open("GET",'http://127.0.0.1:8000/delete/' + id,true);
            xmlhttp.send();
        }
        function move(id){
            window.location.href='http://127.0.0.1:8000/move/' + id
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h2 class="logo">
                        <a href="{% url 'info_assistant:index' %}">Python技术信息助理</a>
                    </h2>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info_assistant:index' %}">首页</a></li>
                        <li><a href="{% url 'info_assistant:show' %}">我的收藏</a></li>
                        <li><a href="{% url 'info_assistant:enter_admin' %}">管理</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        {% if analysis_list %}
            <table class="table table-hover">
            <tr>
                        <td>词语</td>
                        <td>出现频数</td>
                    </tr>
                {% for item in analysis_list %}
                    <tr>
                        <td>{{ item.word }}</td>
                        <td>{{ item.number }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
        {% if info_list %}
            <ul class="list-group">
            {% for info in info_list %}
                    <li class="list-group-item" onclick="">
                        <p class="h3"><a href="{{ info.url }}">{{ info.title }}</a></p>
                        <p>搜索关键字：{{ info.search_key }}</p>
                        <p>数据来源：{{ info.source }}</p>
                        <p>收藏位置：{{ info.category.title }}</p>
                        <p>创建时间：{{ info.create_time }}</p>
                        <button type='button' class="btn btn-success pull-right" onclick="move({{ info.nid }})">移动</button>
                        {% if analysis_list %}
                        {% else %}
                            <button type='button' class="btn btn-danger pull-right" onclick="delete_info({{ info.nid }})">删除</button>
                        {% endif %}
                        <br/><br/>
                    </li>
            {% endfor %}
            </ul>
        {% endif %}
    </div>
</body>
<script>

</script>
</html>

info_assistant/templates/info_assistant/edit_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h2 class="logo">
                        <a href="{% url 'info_assistant:index' %}">Python技术信息助理</a>
                    </h2>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info_assistant:index' %}">首页</a></li>
                        <li><a href="{% url 'info_assistant:show' %}">我的收藏</a></li>
                        <li><a href="{% url 'info_assistant:enter_admin' %}">管理</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <h3 class="">编辑收藏夹名称</h3>
        <form class="navbar-form text-center" action='{% url 'info_assistant:edit_category' %}' method="POST">
            {% csrf_token %}
            <div class="form-group ">
                <input name="category_id" class="hidden" value="{{ id }}">
                <input type="text" name="new_title" class="form-control input-lg col-lg-12" placeholder="输入收藏夹名称">
            </div>
            <button type="submit" class="btn btn-success btn-lg">更名</button>
        </form>
    </div>
</body>
<script>

</script>
</html>

info_assistant/templates/info_assistant/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-default" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h2 class="logo">
                        <a href="{% url 'info_assistant:index' %}">Python技术信息助理</a>
                    </h2>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info_assistant:index' %}">首页</a></li>
                        <li><a href="{% url 'info_assistant:show' %}">我的收藏</a></li>
                        <li><a href="{% url 'info_assistant:enter_admin' %}">管理</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        <h2 class="logo text-center">爬虫搜索</h2>
        <form class="navbar-form text-center" action='{% url 'info_assistant:search' %}' method="POST" role="search">
            {% csrf_token %}
            <div class="form-group ">
                <input type="text" name="keyword" class="form-control input-lg col-lg-12" placeholder="输入关键字">
            </div>
            <button type="submit" class="btn btn-success btn-lg">爬取</button>
        </form>
    </div>
</body>

</html>

info_assistant/templates/info_assistant/move_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <script>
        function choose(id,title){
            document.getElementById("new_category_id").setAttribute('value', id)
            document.getElementById("show").setAttribute('value', title)
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h2 class="logo">
                        <a href="{% url 'info_assistant:index' %}">Python技术信息助理</a>
                    </h2>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info_assistant:index' %}">首页</a></li>
                        <li><a href="{% url 'info_assistant:show' %}">我的收藏</a></li>
                        <li><a href="{% url 'info_assistant:enter_admin' %}">管理</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <h3 class="">移动到其他收藏夹</h3>
        <form class="navbar-form text-center" action='{% url 'info_assistant:move_info_post' %}' method="POST">
            {% csrf_token %}
            <div class="form-group ">
                <input id="new_category_id" class="hidden" name="new_category_id" value="">
                <input name="info_id"  class="hidden" value="{{ info.nid }}">
                <br/><br/><br/>
                {% if category_list %}
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            选择收藏夹
                            <span class="caret"></span>
                        </button>
                        <input id="show" class="form-control input-md" value="" disabled>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            {% for c in category_list %}
                                <li><a href="#" onclick="choose('{{ c.nid }}','{{ c.title }}')">{{ c.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <br/><br/><br/>
                {% endif %}
            <br/><br/><br/>
            </div>

        <br/><br/>
            <button type="submit" class="btn btn-success">移动</button>
        </form>
    </div>
</body>
<script>

</script>
</html>

info_assistant/templates/info_assistant/myCollections.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <script>
        function create_category(){
            window.location.href={% url 'info_assistant:create_category' %}
        }

        function delete_category(nid){
            var xmlhttp;
            xmlhttp=new XMLHttpRequest();
            xmlhttp.onreadystatechange=function()
            {
                if (xmlhttp.readyState==4 && xmlhttp.status==200)
                {
                    alert("删除成功")
                    window.location.href={% url 'info_assistant:show' %}
                }
            }
            xmlhttp.open("GET",'http://127.0.0.1:8000/delete_category/' + nid,true);
            xmlhttp.send();
        }

        function edit_category(nid){
            window.location.href='http://127.0.0.1:8000/edit_interface/' + nid
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h2 class="logo">
                        <a href="{% url 'info_assistant:index' %}">Python技术信息助理</a>
                    </h2>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info_assistant:index' %}">首页</a></li>
                        <li><a href="{% url 'info_assistant:show' %}">我的收藏</a></li>
                        <li><a href="{% url 'info_assistant:enter_admin' %}">管理</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
<div class="container">
  <button type="button" class="btn btn-success pull-right" onclick="create_category()">新建收藏夹</button>
    <br/><br/><br/>
    {% if category_list %}
    <ul class="list-group">
        {% for category in category_list %}
        <li class="list-group-item input-lg" href="#"><a href="{% url 'info_assistant:showall'  category.nid  %}">{{ category.title }}</a>
            <button type="button" class="btn btn-danger pull-right input-sm" onclick="delete_category({{ category.nid }})">删除</button>
            <button type="button" class="btn btn-primary pull-right input-sm" onclick="edit_category({{ category.nid }})">编辑</button>
            <!-- <button type="button" class="btn btn-success pull-right input-sm">查看</button> -->
        </li>
        <br/>
    {% endfor %}
    </ul>
    {% endif %}


</div>
</body>

</html>